// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Run `npm run images` to regenerate after changing src/assets.

import portrait160Avif from "./portrait-160.avif";
import portrait160Webp from "./portrait-160.webp";
import portrait320Avif from "./portrait-320.avif";
import portrait320Webp from "./portrait-320.webp";
import portrait480Avif from "./portrait-480.avif";
import portrait480Webp from "./portrait-480.webp";
import portrait720Avif from "./portrait-720.avif";
import portrait720Webp from "./portrait-720.webp";
import portrait960Avif from "./portrait-960.avif";
import portrait960Webp from "./portrait-960.webp";
import heroBg960Avif from "./heroBg-960.avif";
import heroBg960Webp from "./heroBg-960.webp";
import heroBg1440Avif from "./heroBg-1440.avif";
import heroBg1440Webp from "./heroBg-1440.webp";
import heroBg1920Avif from "./heroBg-1920.avif";
import heroBg1920Webp from "./heroBg-1920.webp";
import heroPortrait280Avif from "./heroPortrait-280.avif";
import heroPortrait280Webp from "./heroPortrait-280.webp";
import heroPortrait460Avif from "./heroPortrait-460.avif";
import heroPortrait460Webp from "./heroPortrait-460.webp";
import heroPortrait560Avif from "./heroPortrait-560.avif";
import heroPortrait560Webp from "./heroPortrait-560.webp";
import heroPortrait760Avif from "./heroPortrait-760.avif";
import heroPortrait760Webp from "./heroPortrait-760.webp";
import cirqRagDiagram800Avif from "./cirqRagDiagram-800.avif";
import cirqRagDiagram800Webp from "./cirqRagDiagram-800.webp";
import cirqRagDiagram1200Avif from "./cirqRagDiagram-1200.avif";
import cirqRagDiagram1200Webp from "./cirqRagDiagram-1200.webp";
import cirqRagDiagram1600Avif from "./cirqRagDiagram-1600.avif";
import cirqRagDiagram1600Webp from "./cirqRagDiagram-1600.webp";
import hpcClusterDiagram1000Avif from "./hpcClusterDiagram-1000.avif";
import hpcClusterDiagram1000Webp from "./hpcClusterDiagram-1000.webp";
import hpcClusterDiagram1500Avif from "./hpcClusterDiagram-1500.avif";
import hpcClusterDiagram1500Webp from "./hpcClusterDiagram-1500.webp";
import hpcClusterDiagram2000Avif from "./hpcClusterDiagram-2000.avif";
import hpcClusterDiagram2000Webp from "./hpcClusterDiagram-2000.webp";
import k8sAutomationDiagram1000Avif from "./k8sAutomationDiagram-1000.avif";
import k8sAutomationDiagram1000Webp from "./k8sAutomationDiagram-1000.webp";
import k8sAutomationDiagram1500Avif from "./k8sAutomationDiagram-1500.avif";
import k8sAutomationDiagram1500Webp from "./k8sAutomationDiagram-1500.webp";
import k8sAutomationDiagram2000Avif from "./k8sAutomationDiagram-2000.avif";
import k8sAutomationDiagram2000Webp from "./k8sAutomationDiagram-2000.webp";
import gpuCloudDiagram1000Avif from "./gpuCloudDiagram-1000.avif";
import gpuCloudDiagram1000Webp from "./gpuCloudDiagram-1000.webp";
import gpuCloudDiagram1500Avif from "./gpuCloudDiagram-1500.avif";
import gpuCloudDiagram1500Webp from "./gpuCloudDiagram-1500.webp";
import gpuCloudDiagram2000Avif from "./gpuCloudDiagram-2000.avif";
import gpuCloudDiagram2000Webp from "./gpuCloudDiagram-2000.webp";
import slaFrameworkDiagram1000Avif from "./slaFrameworkDiagram-1000.avif";
import slaFrameworkDiagram1000Webp from "./slaFrameworkDiagram-1000.webp";
import slaFrameworkDiagram1500Avif from "./slaFrameworkDiagram-1500.avif";
import slaFrameworkDiagram1500Webp from "./slaFrameworkDiagram-1500.webp";
import slaFrameworkDiagram2000Avif from "./slaFrameworkDiagram-2000.avif";
import slaFrameworkDiagram2000Webp from "./slaFrameworkDiagram-2000.webp";
import gpuOptimizationDiagram1000Avif from "./gpuOptimizationDiagram-1000.avif";
import gpuOptimizationDiagram1000Webp from "./gpuOptimizationDiagram-1000.webp";
import gpuOptimizationDiagram1500Avif from "./gpuOptimizationDiagram-1500.avif";
import gpuOptimizationDiagram1500Webp from "./gpuOptimizationDiagram-1500.webp";
import gpuOptimizationDiagram2000Avif from "./gpuOptimizationDiagram-2000.avif";
import gpuOptimizationDiagram2000Webp from "./gpuOptimizationDiagram-2000.webp";

export interface ResponsiveImage {
  /** Widest variant, used as the <img> src fallback. */
  fallback: string;
  sources: { type: string; srcSet: string }[];
  width: number;
  height: number;
}

export const portrait: ResponsiveImage = {
  fallback: portrait960Webp,
  sources: [
    { type: "image/avif", srcSet: `${portrait160Avif} 160w, ${portrait320Avif} 320w, ${portrait480Avif} 480w, ${portrait720Avif} 720w, ${portrait960Avif} 960w` },
    { type: "image/webp", srcSet: `${portrait160Webp} 160w, ${portrait320Webp} 320w, ${portrait480Webp} 480w, ${portrait720Webp} 720w, ${portrait960Webp} 960w` },
  ],
  width: 3456,
  height: 4320,
};

export const heroBg: ResponsiveImage = {
  fallback: heroBg1920Webp,
  sources: [
    { type: "image/avif", srcSet: `${heroBg960Avif} 960w, ${heroBg1440Avif} 1440w, ${heroBg1920Avif} 1920w` },
    { type: "image/webp", srcSet: `${heroBg960Webp} 960w, ${heroBg1440Webp} 1440w, ${heroBg1920Webp} 1920w` },
  ],
  width: 1920,
  height: 1080,
};

export const heroPortrait: ResponsiveImage = {
  fallback: heroPortrait760Webp,
  sources: [
    { type: "image/avif", srcSet: `${heroPortrait280Avif} 280w, ${heroPortrait460Avif} 460w, ${heroPortrait560Avif} 560w, ${heroPortrait760Avif} 760w` },
    { type: "image/webp", srcSet: `${heroPortrait280Webp} 280w, ${heroPortrait460Webp} 460w, ${heroPortrait560Webp} 560w, ${heroPortrait760Webp} 760w` },
  ],
  width: 3000,
  height: 3750,
};

export const cirqRagDiagram: ResponsiveImage = {
  fallback: cirqRagDiagram1600Webp,
  sources: [
    { type: "image/avif", srcSet: `${cirqRagDiagram800Avif} 800w, ${cirqRagDiagram1200Avif} 1200w, ${cirqRagDiagram1600Avif} 1600w` },
    { type: "image/webp", srcSet: `${cirqRagDiagram800Webp} 800w, ${cirqRagDiagram1200Webp} 1200w, ${cirqRagDiagram1600Webp} 1600w` },
  ],
  width: 2752,
  height: 1536,
};

export const hpcClusterDiagram: ResponsiveImage = {
  fallback: hpcClusterDiagram2000Webp,
  sources: [
    { type: "image/avif", srcSet: `${hpcClusterDiagram1000Avif} 1000w, ${hpcClusterDiagram1500Avif} 1500w, ${hpcClusterDiagram2000Avif} 2000w` },
    { type: "image/webp", srcSet: `${hpcClusterDiagram1000Webp} 1000w, ${hpcClusterDiagram1500Webp} 1500w, ${hpcClusterDiagram2000Webp} 2000w` },
  ],
  width: 2200,
  height: 2278,
};

export const k8sAutomationDiagram: ResponsiveImage = {
  fallback: k8sAutomationDiagram2000Webp,
  sources: [
    { type: "image/avif", srcSet: `${k8sAutomationDiagram1000Avif} 1000w, ${k8sAutomationDiagram1500Avif} 1500w, ${k8sAutomationDiagram2000Avif} 2000w` },
    { type: "image/webp", srcSet: `${k8sAutomationDiagram1000Webp} 1000w, ${k8sAutomationDiagram1500Webp} 1500w, ${k8sAutomationDiagram2000Webp} 2000w` },
  ],
  width: 2200,
  height: 1595,
};

export const gpuCloudDiagram: ResponsiveImage = {
  fallback: gpuCloudDiagram2000Webp,
  sources: [
    { type: "image/avif", srcSet: `${gpuCloudDiagram1000Avif} 1000w, ${gpuCloudDiagram1500Avif} 1500w, ${gpuCloudDiagram2000Avif} 2000w` },
    { type: "image/webp", srcSet: `${gpuCloudDiagram1000Webp} 1000w, ${gpuCloudDiagram1500Webp} 1500w, ${gpuCloudDiagram2000Webp} 2000w` },
  ],
  width: 2200,
  height: 2166,
};

export const slaFrameworkDiagram: ResponsiveImage = {
  fallback: slaFrameworkDiagram2000Webp,
  sources: [
    { type: "image/avif", srcSet: `${slaFrameworkDiagram1000Avif} 1000w, ${slaFrameworkDiagram1500Avif} 1500w, ${slaFrameworkDiagram2000Avif} 2000w` },
    { type: "image/webp", srcSet: `${slaFrameworkDiagram1000Webp} 1000w, ${slaFrameworkDiagram1500Webp} 1500w, ${slaFrameworkDiagram2000Webp} 2000w` },
  ],
  width: 2200,
  height: 1361,
};

export const gpuOptimizationDiagram: ResponsiveImage = {
  fallback: gpuOptimizationDiagram2000Webp,
  sources: [
    { type: "image/avif", srcSet: `${gpuOptimizationDiagram1000Avif} 1000w, ${gpuOptimizationDiagram1500Avif} 1500w, ${gpuOptimizationDiagram2000Avif} 2000w` },
    { type: "image/webp", srcSet: `${gpuOptimizationDiagram1000Webp} 1000w, ${gpuOptimizationDiagram1500Webp} 1500w, ${gpuOptimizationDiagram2000Webp} 2000w` },
  ],
  width: 2200,
  height: 1629,
};
