// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Run `npm run images` to regenerate after changing src/assets.

import portrait160Avif from "./portrait-160.avif";
import portrait160Webp from "./portrait-160.webp";
import portrait320Avif from "./portrait-320.avif";
import portrait320Webp from "./portrait-320.webp";
import portrait480Avif from "./portrait-480.avif";
import portrait480Webp from "./portrait-480.webp";
import portrait720Avif from "./portrait-720.avif";
import portrait720Webp from "./portrait-720.webp";
import portrait960Avif from "./portrait-960.avif";
import portrait960Webp from "./portrait-960.webp";
import heroBg960Avif from "./heroBg-960.avif";
import heroBg960Webp from "./heroBg-960.webp";
import heroBg1440Avif from "./heroBg-1440.avif";
import heroBg1440Webp from "./heroBg-1440.webp";
import heroBg1920Avif from "./heroBg-1920.avif";
import heroBg1920Webp from "./heroBg-1920.webp";
import cirqRagDiagram800Avif from "./cirqRagDiagram-800.avif";
import cirqRagDiagram800Webp from "./cirqRagDiagram-800.webp";
import cirqRagDiagram1200Avif from "./cirqRagDiagram-1200.avif";
import cirqRagDiagram1200Webp from "./cirqRagDiagram-1200.webp";
import cirqRagDiagram1600Avif from "./cirqRagDiagram-1600.avif";
import cirqRagDiagram1600Webp from "./cirqRagDiagram-1600.webp";

export interface ResponsiveImage {
  /** Widest variant, used as the <img> src fallback. */
  fallback: string;
  sources: { type: string; srcSet: string }[];
  width: number;
  height: number;
}

export const portrait: ResponsiveImage = {
  fallback: portrait960Webp,
  sources: [
    { type: "image/avif", srcSet: `${portrait160Avif} 160w, ${portrait320Avif} 320w, ${portrait480Avif} 480w, ${portrait720Avif} 720w, ${portrait960Avif} 960w` },
    { type: "image/webp", srcSet: `${portrait160Webp} 160w, ${portrait320Webp} 320w, ${portrait480Webp} 480w, ${portrait720Webp} 720w, ${portrait960Webp} 960w` },
  ],
  width: 3456,
  height: 4320,
};

export const heroBg: ResponsiveImage = {
  fallback: heroBg1920Webp,
  sources: [
    { type: "image/avif", srcSet: `${heroBg960Avif} 960w, ${heroBg1440Avif} 1440w, ${heroBg1920Avif} 1920w` },
    { type: "image/webp", srcSet: `${heroBg960Webp} 960w, ${heroBg1440Webp} 1440w, ${heroBg1920Webp} 1920w` },
  ],
  width: 1920,
  height: 1080,
};

export const cirqRagDiagram: ResponsiveImage = {
  fallback: cirqRagDiagram1600Webp,
  sources: [
    { type: "image/avif", srcSet: `${cirqRagDiagram800Avif} 800w, ${cirqRagDiagram1200Avif} 1200w, ${cirqRagDiagram1600Avif} 1600w` },
    { type: "image/webp", srcSet: `${cirqRagDiagram800Webp} 800w, ${cirqRagDiagram1200Webp} 1200w, ${cirqRagDiagram1600Webp} 1600w` },
  ],
  width: 2752,
  height: 1536,
};
