// Generates responsive AVIF/WebP variants for the source images and emits a typed
// manifest at src/assets/optimized/manifest.ts.
//
// Why: the repo shipped ~8 MB of images for a text site — a 5.8 MB PNG diagram and
// a 2.0 MB JPEG rendered as a 64px avatar. Run `npm run images` after adding or
// replacing anything in src/assets, then commit the output.

import sharp from "sharp";
import { mkdir, stat, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = resolve(root, "src/assets");
const outDir = resolve(root, "src/assets/optimized");

/** Widths are the sizes each image is actually displayed at, doubled for 2x screens. */
const TARGETS = [
  { file: "me.jpg", name: "portrait", widths: [160, 320, 480, 720, 960], quality: 72 },
  { file: "hero-bg.jpg", name: "heroBg", widths: [960, 1440, 1920], quality: 62 },
  // The landing hero's own portrait: a better frame than me.jpg, orientation
  // corrected and gently graded. Higher quality than the small avatar because
  // it is displayed several times larger.
  { file: "portrait-hero.jpg", name: "heroPortrait", widths: [280, 460, 560, 760], quality: 80 },
  // A diagram: text legibility matters more than file size, so quality stays high.
  { file: "Cirq-RAG-Agent.png", name: "cirqRagDiagram", widths: [800, 1200, 1600], quality: 82 },
  // The architecture diagrams. Denser than the RAG diagram — small labels have to
  // survive, so they carry a wider top variant and the same high quality.
  { file: "arch-hpc-cluster.png", name: "hpcClusterDiagram", widths: [1000, 1500, 2000], quality: 82 },
  { file: "arch-k8s-automation.png", name: "k8sAutomationDiagram", widths: [1000, 1500, 2000], quality: 82 },
  { file: "arch-gpu-cloud.png", name: "gpuCloudDiagram", widths: [1000, 1500, 2000], quality: 82 },
  { file: "arch-sla-framework.png", name: "slaFrameworkDiagram", widths: [1000, 1500, 2000], quality: 82 },
  { file: "arch-gpu-optimization.png", name: "gpuOptimizationDiagram", widths: [1000, 1500, 2000], quality: 82 },
];

const FORMATS = [
  { ext: "avif", encode: (pipeline, quality) => pipeline.avif({ quality: quality - 8, effort: 6 }) },
  { ext: "webp", encode: (pipeline, quality) => pipeline.webp({ quality }) },
];

async function fileSize(path) {
  return (await stat(path)).size;
}

async function run() {
  await mkdir(outDir, { recursive: true });

  const manifest = [];
  let before = 0;
  let after = 0;

  for (const target of TARGETS) {
    const input = resolve(srcDir, target.file);
    before += await fileSize(input);

    const meta = await sharp(input).metadata();
    const variants = [];

    for (const width of target.widths) {
      if (meta.width && width > meta.width) continue; // never upscale
      for (const format of FORMATS) {
        const outName = `${target.name}-${width}.${format.ext}`;
        const outPath = resolve(outDir, outName);
        const pipeline = sharp(input).resize({ width, withoutEnlargement: true });
        const info = await format.encode(pipeline, target.quality).toFile(outPath);
        after += info.size;
        variants.push({ file: outName, width: info.width, format: format.ext });
      }
    }

    manifest.push({
      name: target.name,
      source: target.file,
      intrinsicWidth: meta.width ?? 0,
      intrinsicHeight: meta.height ?? 0,
      variants,
    });
  }

  const lines = [];
  lines.push("// GENERATED by scripts/optimize-images.mjs — do not edit by hand.");
  lines.push("// Run `npm run images` to regenerate after changing src/assets.");
  lines.push("");

  for (const entry of manifest) {
    for (const variant of entry.variants) {
      lines.push(
        `import ${identifier(entry.name, variant)} from "./${variant.file}";`,
      );
    }
  }

  lines.push("");
  lines.push("export interface ResponsiveImage {");
  lines.push("  /** Widest variant, used as the <img> src fallback. */");
  lines.push("  fallback: string;");
  lines.push("  sources: { type: string; srcSet: string }[];");
  lines.push("  width: number;");
  lines.push("  height: number;");
  lines.push("}");
  lines.push("");

  for (const entry of manifest) {
    const byFormat = new Map();
    for (const variant of entry.variants) {
      if (!byFormat.has(variant.format)) byFormat.set(variant.format, []);
      byFormat.get(variant.format).push(variant);
    }
    const webp = byFormat.get("webp") ?? [];
    const widest = webp[webp.length - 1];

    lines.push(`export const ${entry.name}: ResponsiveImage = {`);
    lines.push(`  fallback: ${identifier(entry.name, widest)},`);
    lines.push("  sources: [");
    for (const [format, variants] of byFormat) {
      const srcSet = variants
        .map((v) => `\${${identifier(entry.name, v)}} ${v.width}w`)
        .join(", ");
      lines.push(`    { type: "image/${format}", srcSet: \`${srcSet}\` },`);
    }
    lines.push("  ],");
    lines.push(`  width: ${entry.intrinsicWidth},`);
    lines.push(`  height: ${entry.intrinsicHeight},`);
    lines.push("};");
    lines.push("");
  }

  await writeFile(resolve(outDir, "manifest.ts"), lines.join("\n"), "utf8");

  console.log(`sources: ${(before / 1024 / 1024).toFixed(2)} MB`);
  console.log(`variants: ${(after / 1024 / 1024).toFixed(2)} MB across ${manifest.reduce((n, e) => n + e.variants.length, 0)} files`);
  for (const entry of manifest) {
    console.log(`  ${entry.name}: ${entry.variants.length} variants (${entry.intrinsicWidth}x${entry.intrinsicHeight} source)`);
  }
}

function identifier(name, variant) {
  return `${name}${variant.width}${variant.format.charAt(0).toUpperCase()}${variant.format.slice(1)}`;
}

await run();
